set ai
set number
set tabstop=4
set shiftwidth=4
set fdm=marker
set mouse-=a
syntax on
color darkblue
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
inoremap <c-@> <c-x><c-o>
map <F5> :w<CR>:!php -l %<CR>
